config/routes.rb
TomatoesApp::Application.routes.draw do
  resources :tags, :only => [:index, :show]

  resources :projects

  resources :statistics, :only => :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  resources :rankings, :only => :index

  resources :tomatoes do
    member do
      post 'track'
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    resources :tomatoes, :only => [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin/:provider' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

  root :to => "welcome#index"

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  # GET /statistics
  def index
    @users        = User.count
    @tomatoes     = Tomato.count
    @first_tomato = Tomato.order_by([[:created_at, :desc]]).last || Tomato.new(:created_at => Time.now)
  end

  # GET /statistics/users_by_tomatoes.json
  def users_by_tomatoes
    respond_with_json do
      Rails.cache.fetch('users_by_tomatoes', :expires_in => 1.day) do
        User.by_tomatoes(User.all)
      end
    end
  end

  # GET /statistics/total_users_by_day.json
  def total_users_by_day
    respond_with_json do
      Rails.cache.fetch('total_users_by_day', :expires_in => 1.day) do
        User.total_by_day(User.excludes(:created_at => nil))
      end
    end
  end

  # GET /statistics/users_by_day.json
  def users_by_day
    respond_with_json do
      Rails.cache.fetch('users_by_day', :expires_in => 1.day) do
        User.by_day(User.excludes(:created_at => nil))
      end
    end
  end

  # GET /statistics/tomatoes_by_day.json
  def tomatoes_by_day
    tomatoes_count = 0

    respond_with_json do
      Rails.cache.fetch('tomatoes_by_day', :expires_in => 1.day) do
        Tomato.by_day(Tomato.all) do |tomatoes_by_day|
          tomatoes_count += tomatoes_by_day ? tomatoes_by_day.size : 0
        end
      end
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/index.html.erb
<% content_for :head do %>
  <%= javascript_tag do %>
    var TOTAL_USERS_BY_DAY_STATISTICS_URL = '<%= total_users_by_day_statistics_url(:format => :json) %>',
        USERS_BY_DAY_STATISTICS_URL = '<%= users_by_day_statistics_url(:format => :json) %>'
        USERS_BY_TOMATOES_STATISTICS_URL = '<%= users_by_tomatoes_statistics_url(:format => :json) %>',
        TOMATOES_BY_DAY_STATISTICS_URL = '<%= tomatoes_by_day_statistics_url(:format => :json) %>';
  <% end %>
<% end %>

<% content_for :foot do %>
  <%= javascript_include_tag "statistics" %>
<% end %>

<h1>Statistics</h1>

<h2>Users</h2>
<p>
  <%= pluralize(@users, 'user') %><br/>
  <% if @users > 0 %>
    about <%= pluralize(@tomatoes/@users, 'tomato') %> per user
  <% end %>
</p>

<h2>Users by day</h2>
<div class="chart" id="users_by_day">
  <%= image_tag 'loading.gif', :class => 'loading' %>
</div>

<!--
<h2>Users by tomatoes</h2>
<div class="chart" id="users_by_tomatoes">
  <%= image_tag 'loading.gif', :class => 'loading' %>
</div>
-->

<h2>Tomatoes</h2>
<p>
  <%= pluralize(@tomatoes, 'tomato') %><br/>
  about <%= humanize(@tomatoes*Tomato::DURATION) %> of work<br/>
  about <%= number_with_precision(@tomatoes/((Time.zone.now - @first_tomato.created_at) / 3600)) %> tomatoes per hour
</p>

<h2>Tomatoes by day</h2>
<div class="chart" id="tomatoes_by_day">
  <%= image_tag 'loading.gif', :class => 'loading' %>
</div>