config/routes.rb
TomatoesApp::Application.routes.draw do
  resources :tags, :only => [:index, :show]

  resources :projects

  resources :statistics, :only => :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  resources :rankings, :only => :index

  resources :tomatoes do
    member do
      post 'track'
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    resources :tomatoes, :only => [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin/:provider' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

  root :to => "welcome#index"

end

app/models/user.rb
# encoding: UTF-8

class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Chartable
  include Workable

  CURRENCIES = {
    'USD' => '$',
    'EUR' => '€',
    'JPY' => '¥',
    'GBP' => '£',
    'CHF' => 'Fr.'
  }

  DEFAULT_COLOR      = '#000000'
  DEFAULT_CURRENCY   = 'USD'
  DEFAULT_IMAGE_FILE = 'user.png'
  DEFAULT_VOLUME     = 2
  DEFAULT_TICKING    = false
  
  # authorization fields (deprecated)
  field :provider,    :type => String
  field :uid,         :type => String
  field :token,       :type => String
  field :gravatar_id, :type => String

  field :name,      :type => String
  field :email,     :type => String
  field :image,     :type => String
  field :time_zone, :type => String
  field :color,     :type => String
  field :volume,    :type => Integer
  field :ticking,   :type => Boolean

  field :work_hours_per_day,  :type => Integer
  field :average_hourly_rate, :type => Float
  field :currency,            :type => String
  
  # attr_accessible :provider, :uid, :token, :gravatar_id
  attr_accessible :name, :email, :image, :time_zone, :color, :work_hours_per_day, :average_hourly_rate, :currency, :volume, :ticking

  validates_format_of :color, with: /\A#[A-Fa-f0-9]{6}\Z/, allow_blank: true
  validates_numericality_of :volume, greater_than_or_equal_to: 0, less_than: 4, allow_blank: true

  validates_inclusion_of :currency, :in => CURRENCIES.keys
  validates_numericality_of :work_hours_per_day, greater_than: 0, allow_blank: true
  validates_numericality_of :average_hourly_rate, greater_than: 0, allow_blank: true
  
  embeds_many :authorizations
  has_many :tomatoes
  has_many :projects

  index 'authorizations.uid'
  index 'authorizations.provider'
  
  def self.find_by_omniauth(auth)
    any_of(
      {:authorizations => {
        '$elemMatch' => {
          :provider => auth['provider'].to_s,
          :uid      => auth['uid'].to_s }}},
      {:provider => auth['provider'], :uid => auth['uid']}
    ).first
  end
  
  def self.create_with_omniauth!(auth)
    user = User.new(omniauth_attributes(auth))
    user.authorizations.build(Authorization.omniauth_attributes(auth))
    user.save!
    user
  end
  
  def update_omniauth_attributes!(auth)
    # migrate users' data gracefully
    update_attributes!(omniauth_attributes(auth))

    if authorization = authorization_by_provider(auth['provider'])
      authorization.update_attributes!(Authorization.omniauth_attributes(auth))
    else
      # merge one more authorization provider
      authorizations.create!(Authorization.omniauth_attributes(auth))
    end
  end
  
  def self.omniauth_attributes(auth)
    attributes = {}
    
    attributes.merge!({
      name:  auth['info']['name'],
      email: auth['info']['email'],
      image: auth['info']['image']
    }) if auth['info']
    
    attributes
  end

  def omniauth_attributes(auth)
    attributes = self.class.omniauth_attributes(auth)

    [:name, :email].each do |attribute|
      attributes.delete(attribute) if send(attribute) && !send(attribute).empty?
    end
    
    attributes
  end

  def authorization_by_provider(provider)
    authorizations.where(provider: provider).first
  end

  def tomatoes_after(time)
    tomatoes.where(:created_at => {'$gte' => time}).order_by([[:created_at, :desc]])
  end

  def self.by_tomatoes(users)
    to_tomatoes_bars(users) do |users_by_tomatoes|
      users_by_tomatoes ? users_by_tomatoes.size : 0
    end
  end

  def self.by_day(users)
    to_lines(users) do |users_by_day|
      users_by_day ? users_by_day.size : 0
    end
  end

  def self.total_by_day(users)
    # NOTE: first 1687 users lack of created_at value
    users_count = 1687

    to_lines(users) do |users_by_day|
      users_count += users_by_day ? users_by_day.size : 0
    end
  end

  def color
    color_value = read_attribute(:color)
    color_value && !color_value.empty? ? color_value : User::DEFAULT_COLOR
  end

  def volume
    volume_value = read_attribute(:volume)
    volume_value.present? ? volume_value : User::DEFAULT_VOLUME
  end

  def ticking
    ticking_value = read_attribute(:ticking)
    ticking_value.present? ? ticking_value : User::DEFAULT_TICKING
  end

  def currency
    currency_value = read_attribute(:currency)
    currency_value && !currency_value.empty? ? currency_value : User::DEFAULT_CURRENCY
  end

  def nickname
    authorizations.first.try(:nickname)
  end

  def image_file
    image_value = read_attribute(:image) || authorizations.first.try(:image)
    image_value && !image_value.empty? ? image_value : User::DEFAULT_IMAGE_FILE
  end

  def currency_unit
    User::CURRENCIES[currency]
  end

  def estimated_revenues
    work_time*Workable::TOMATO_TIME_FACTOR/60/60 * average_hourly_rate.to_f if average_hourly_rate
  end

  def tomatoes_counter(time_period)
    tomatoes_after(Time.zone.now.send("beginning_of_#{time_period}")).count
  end

  def tomatoes_counters
    Hash[[:day, :week, :month].map do |time_period|
      [time_period, tomatoes_counter(time_period)]
    end]
  end

  def any_of_conditions(tags)
    tags.map { |tag| {tags: tag} }
  end

  def tomatoes_by_tags(tags)
    any_of_conditions(tags).empty? ? [] : tomatoes.any_of(any_of_conditions(tags))
  end
end

app/controllers/users_controller.rb
class UsersController < ResourceController
  before_filter :authenticate_user!, :except => :show
  before_filter :same_user!, :except => :show
  
  # GET /users/1/edit
  def edit
  end
  
  # PUT /users/1
  # PUT /users/1.xml
  def update
    update_resource(@user)
  end
  
  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    destroy_resource(@user, root_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image(user, size = 24)
    image_tag user.image_file, :width => size
  end
  
  def user_name(user)
    link_to user.name || user.nickname, user, :class => 'user_name'
  end

  def hex_to_rgba(hex)
    m = hex.match /#(..)(..)(..)/
    "rgba(#{m[1].hex}, #{m[2].hex}, #{m[3].hex}, .7)"
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %></br>
    <%= f.text_field :email %>
    <div class="hint">Your email address.</div>
  </div>
  <div class="field">
    <%= f.label :time_zone %></br>
    <%= time_zone_select 'user', 'time_zone', nil, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :currency %></br>
    <%= f.select(:currency, options_for_select(User::CURRENCIES.invert, @user.currency)) %>
  </div>
  <div class="field">
    <%= f.label :work_hours_per_day %></br>
    <%= f.text_field :work_hours_per_day %>
    <div class="hint">How many hours do you work per day? Example: <em>8</em></div>
  </div>
  <div class="field">
    <%= f.label :average_hourly_rate %></br>
    <%= f.text_field :average_hourly_rate %>
    <div class="hint">How much do you charge per hour? Example: <em>35.5</em></div>
  </div>
  <div class="field">
    <%= f.label :volume %></br>
    <%= f.range_field :volume, :min => 0, :max => 3 %>
    <div class="hint">Default timer volume. <em>0</em> is <em>mute</em>, <em>3</em> is <em>max volume</em>.</div>
  </div>
  <div class="field">
    <%= f.check_box :ticking %><%= f.label :ticking %>
    <div class="hint">Timer ticking effect.</div>
  </div>

  <div class="field block">
    <div class="left">
      <%= f.label :color %></br>
      <%= f.text_field :color %>
      <div class="hint">An hexadecimal color code. Example: <em>#ccff00</em></div>
    </div>
    <div id="colorpicker" class="left"></div>
  </div>
  
  <div class="actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="left profile_image">
  <%= profile_image(user) %>
</div>
<%= user_name(user) %>

app/views/users/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "users" %>
<% end %>

<h3>Editing profile</h3>

<div id="request_notification_permission">
  <%= link_to "", "#" %>
  <div id="notification_not_supported" style="display: none">Note: notifications are not supported by your browser.</div>
</div>

<%= render 'form' %>

<%= link_to 'Back', current_user %>

app/views/users/show.html.erb
<% content_for :head do %>
  <%= javascript_tag do %>
    var BY_DAY_USER_TOMATOES_URL = '<%= by_day_user_tomatoes_url(@user, :format => :json) %>',
        BY_HOUR_USER_TOMATOES_URL = '<%= by_hour_user_tomatoes_url(@user, :format => :json) %>';
  <% end %>
<% end %>

<% content_for :foot do %>
  <%= javascript_include_tag "users", "users_charts" %>
<% end %>

<div id="user">
  <div class="block">
    <div class="profile left">
      <div class="block">
        <h2><%= user_name(@user) %></h2>
        <div class="left profile_image size48">
          <%= profile_image(@user, 48) %>
        </div>
        <div class="left profile_info">
          Tomatoes: <%= @user.tomatoes.size %></br>
          <% @user.authorizations.each do |authorization| %>
            <%= link_to authorization.url, authorization.url %><br/>
          <% end %>
          <%= content_for_user(@user) do %>
            <div id="request_notification_permission">
              <%= link_to "", "#" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= content_for_user(@user) do %>
      <% ['twitter', 'github'].each do |provider| %>
        <%= render :partial => 'authorizations/authorization', :locals => {:provider => provider, :user => @user} %>
      <% end %>
    <% end %>
  </div>

  <%= content_for_user(@user) do %>
    <p>
      <b>Time Zone:</b> <%= @user.time_zone %><br/>
      <b>Currency:</b> <%= @user.currency %>
    </p>
    <p>
      <b>Work hours per day:</b> <%= @user.work_hours_per_day %><br/>
      <b>Average hourly rate:</b> <%= hourly_rate(@user.average_hourly_rate, @user.currency) %><br/>
      <b>Effective work time:</b> <%= distance_of_time_in_words(@user.effective_work_time) if @user.effective_work_time %><br/>
      <b>Estimated revenues:</b> <%= money(@user.estimated_revenues, @user.currency_unit) %>
    </p>
    <p>
      <%= link_to 'Your tomatoes', tomatoes_path %> |
      <%= link_to 'Your projects', projects_path %> |
      <%= link_to 'Your tags', tags_path %> |
      <%= link_to 'Export your tomatoes (csv)', tomatoes_path(format: :csv) %> |
      <%= link_to 'Edit profile', edit_user_path(@user) %>
    </p>
  <% end %>
</div>

<h2>Tomatoes by day</h2>
<div class="chart" id="tomatoes_by_day">
  <%= image_tag 'loading.gif', :class => 'loading' %>
</div>
<div class="chart overview" id="tomatoes_by_day_overview"></div>

<h2>Tomatoes by hour</h2>
<div class="chart" id="tomatoes_by_hour">
  <%= image_tag 'loading.gif', :class => 'loading' %>
</div>