config/routes.rb
TomatoesApp::Application.routes.draw do
  resources :tags, :only => [:index, :show]

  resources :projects

  resources :statistics, :only => :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  resources :rankings, :only => :index

  resources :tomatoes do
    member do
      post 'track'
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    resources :tomatoes, :only => [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin/:provider' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

  root :to => "welcome#index"

end

app/views/shared/_adv_leaderboard.html.erb
<!-- Tomatoes (728x90) -->
<ins class="adsbygoogle"
     style="display:block;width:728px;height:90px;margin:30px auto"
     data-ad-client="ca-pub-7194529311513014"
     data-ad-slot="8775901073"></ins>

<%= javascript_tag do %>
  (adsbygoogle = window.adsbygoogle || []).push({});
<% end %>

app/views/shared/_adv_rectangle.html.erb
<!-- Tomatoes (300x250) -->
<ins class="adsbygoogle"
     style="display:block;width:300px;height:250px;margin:10px auto"
     data-ad-client="ca-pub-7194529311513014"
     data-ad-slot="8636300276"></ins>

<%= javascript_tag do %>
  (adsbygoogle = window.adsbygoogle || []).push({});
<% end %>

app/views/shared/_announcement.html.erb
<% if ENV['ANNOUNCEMENT'] %>
  <div id="announcement">
    <div class="title">Announcement</div>
    <%= raw(ENV['ANNOUNCEMENT']) %>
  </div>
<% end %>

app/views/shared/_counter.html.erb
<div class="<%= css_class %> counter button">
  <div class="counter_value"><%= value %></div>
  <div class="counter_label"><%= label %></div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, msg| %>
  <div class="<%= key %>"><p><%= msg %></p></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container block">
  <div class="left">
    <div>
      <a class="FlattrButton" style="display:none;" rev="flattr;button:compact;" href="http://tomatoes.heroku.com"></a>
      <noscript><a href="http://flattr.com/thing/376437/Tomatoes" target="_blank">
      <img src="http://api.flattr.com/button/flattr-badge-large.png" alt="Flattr this" title="Flattr this" border="0" /></a></noscript>
    </div>
    <div id="add_to_chrome">
      <%= link_to 'https://chrome.google.com/webstore/detail/jijbhneeenepenoolcdalnekggeialeo' do %>
        <%= image_tag("chrome-icon.png") %>
        Add to Chrome
      <% end %>
    </div>
    <div>
      Follow updates <%= link_to "@tomatoesapp", "http://twitter.com/tomatoesapp" %><br/>
      <%= link_to "Tomatoes", TomatoesApp::REPO %> - <%= link_to "version #{TomatoesApp::VERSION}", "#{TomatoesApp::REPO}/tree/#{TomatoesApp::VERSION}" %>
    </div>
    <div class="trademarks">
      This application is not affiliated, associated or endorsed by the Pomodoro Technique® or Francesco Cirillo.<br/>
      The Pomodoro Technique® and Pomodoro™ are registered trademarks by Francesco Cirillo.
    </div>
  </div>
  <div class="right">
    <%= render partial: 'shared/ranking_links' %><br/>
    <%= link_to "How to", page_path('how_to') %>,
    <%= link_to "Statistics", statistics_path %><br/>
    <%= link_to "Terms of service", page_path('terms') %>,
    <%= link_to "Privacy policy", page_path('privacy') %>,
    <%= link_to "Imprint", page_path('imprint') %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="block container">
  <div id="logo" class="block auth left">
    <div class="text">
      <h1><%= link_to "Tomatoes", root_path %></h1>
    </div>
  </div>
  <% if current_user %>
    <div id="user_container" class="right">
      <div class="block">
        <div class="left user">
          <%= render :partial => 'users/user', :locals => {:user => current_user} %>
        </div>
        <div class="left sign_out"><%= link_to "Sign out", signout_path %></div>
      </div>
    </div>
  <% else %>
    <div id="sign_in_container" class="right">
      <%= link_to signin_path('github') do %>
        <%= image_tag("github.png", :width => "24") %>
        Sign in with GitHub
      <% end %>
      or
      <%= link_to signin_path('twitter') do %>
        <%= image_tag("twitter.png", :width => "24") %>
        Sign in with Twitter
      <% end %>
    </div>
  <% end %>
</header>

app/views/shared/_public_header.html.erb
<header class="block container">
  <div id="logo" class="start">
    <div class="text">
      <h1><%= link_to "Tomatoes", root_path %></h1>
      <h2>Pomodoro technique<sup>®</sup> time tracker</h2>
    </div>
    <div id="sponsors" class="block">
      <p class="left">Sponsored by</p>
      <a id="mongohq" class="left" href="http://mongohq.com">MongoHQ</a>
    </div>
  </div>
</header>

app/views/shared/_ranking_links.html.erb
Leaderboards:
<%= link_to "Today", rankings_path(:time_period => 'today') %>,
<%= link_to "This week", rankings_path(:time_period => 'this_week') %>,
<%= link_to "This month", rankings_path(:time_period => 'this_month') %>,
<%= link_to "All time", rankings_path(:time_period => 'all_time') %>