config/routes.rb
TomatoesApp::Application.routes.draw do
  resources :tags, :only => [:index, :show]

  resources :projects

  resources :statistics, :only => :index do
    collection do
      get 'users_by_tomatoes'
      get 'total_users_by_day'
      get 'users_by_day'
      get 'tomatoes_by_day'
    end
  end

  resources :rankings, :only => :index

  resources :tomatoes do
    member do
      post 'track'
    end
  end

  resources :users, :only => [:show, :edit, :update, :destroy] do
    resources :tomatoes, :only => [] do
      collection do
        get 'by_day'
        get 'by_hour'
      end
    end
  end
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin/:provider' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'

  root :to => "welcome#index"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout Proc.new { |controller| controller.user_signed_in? ? 'application' : 'public' }

  def index
    if current_user
      @tomato         = current_user.tomatoes.build
      @tomatoes       = current_user.tomatoes_after(Time.zone.now.beginning_of_day)
      @tomatoes_count = current_user.tomatoes_counters
      @projects       = @tomatoes.collect(&:projects).flatten.uniq
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def counter_label(time_period)
    case time_period
    when :day
      "Today"
    when :week
      "This week"
    when :month
      "This month"
    end
  end
end

app/views/welcome/_dashboard.html.erb
<div id="index" class="block">
  <div class="block">
    <div class="left">
      <div id="tomatoes_list">
        <%= render :partial => 'tomatoes_list', :locals => {:high => nil} %>
      </div>
      <div id="projects_list">
        <%= render :partial => 'projects_list' %>
      </div>
    </div>

    <div class="right">
      <div id="user_statistics">
        <%= render :partial => 'user_statistics' %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_projects_list.html.erb
<% unless @projects.empty? %>
  <h3><%= link_to "Today's projects", projects_path %></h3>
  <table>
    <%= render partial: 'projects/project', collection: @projects %>
  </table>
<% else %>
  <p>You're not working on any project</p>
  <p>Create a <%= link_to "new project", new_project_path %> to start collecting aggregate statistics</p>
<% end %>

app/views/welcome/_public.html.erb
<div id="intro">
  <p>Tomatoes is a <i>pomodoro tracker</i>, a Pomodoro technique® driven time tracker.</p>
  <p>Use the Pomodoro technique® to track your working time in 25-minutes slot called <i>pomodoro</i>.</p>
</div>

<div class="sign_in block">
  <%= link_to signin_path('github'), :class => "button" do %>
    <%= image_tag("github.png", :width => "32") %>
    Sign in with GitHub
  <% end %>
  or
  <%= link_to signin_path('twitter'), :class => "button" do %>
    <%= image_tag("twitter.png", :width => "32") %>
    Sign in with Twitter
  <% end %>
  <p>Sign in to start tracking your pomodoros.</p>
</div>

app/views/welcome/_tomatoes_list.html.erb
<% unless @tomatoes.empty? %>
  <h3><%= link_to "Today's tomatoes", tomatoes_path %></h3>
  <table>
    <%= render partial: 'tomatoes/tomato', collection: @tomatoes, locals: {high: high} %>
  </table>
<% else %>
  <p>No tomatoes here</p>
  <p>Click the Start button when you're ready to start your first tomato</p>
<% end %>

app/views/welcome/_tomatoes_timer.html.erb
<% content_for :head do %>
  <%= javascript_tag do %>
    var tomatoDuration = <%= Tomato::DURATION/60.0 %>;
    var tomatoBreakDuration = <%= Tomato::BREAK_DURATION/60.0 %>;
    var tomatoNotificationIcon = '<%= asset_path('notification_icon.png') %>';
    var volume = <%= (current_user ? current_user.volume : User::DEFAULT_VOLUME)*25 %>;
    var currentUser = <%= current_user ? 'true' : 'false' %>;
    var DEBUG = <%= Rails.env.development? %>;
  <% end %>
  <%= javascript_include_tag "TT" %>

  <style type="text/css">
    #progress_bar {
      background-color: <%= hex_to_rgba(current_user ? current_user.color : User::DEFAULT_COLOR) %>;
    }
  </style>
<% end %>

<div id="progress_bar">
  <div id="timer_container">
    <div id="timer" style="display: none">
      <div id="ticking_sound_switch_container">
        <%= check_box_tag('ticking_sound_switch', '1', current_user ? current_user.ticking : User::DEFAULT_TICKING, :id => 'ticking_sound_switch') %>
        <label for="ticking_sound_switch">Ticking sound</label>
      </div>
      <div class="volume right block unselectable">
        <div class="down left">-</div>
        <div id="volume_icon" class="mute_toggle left"></div>
        <div class="up left">+</div>
      </div>
      <% if current_user %>
        <%= render :partial => 'shared/adv_rectangle' %>
      <% end %>
      <div id="timer_counter"></div>
      <%= link_to "Reset", "#", :id => "reset", :class => "button" %>
      <p id="reset_hint">or press esc</p>
    </div>
    <div id="new_tomato_form" style="display: none">
    <% if current_user %>
      <%= render 'tomatoes/form', remote: true %>
    <% else %>
      <div id="tomato_signin" class="block">
        <h2>Sign in to start tracking your work.</h2>
        <%= link_to signin_path('github'), :class => "button" do %>
          <%= image_tag("github.png", :width => "24") %>
          GitHub
        <% end %>
        or
        <%= link_to signin_path('twitter'), :class => "button" do %>
          <%= image_tag("twitter.png", :width => "24") %>
          Twitter
        <% end %>
        <div id="cancel">
          <%= link_to "Cancel", "#", :id => "reset_signin", :class => "button" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<div id="start_container">
  <%= link_to "Start", "#", :id => "start", :class => "button" %>
  <p id="start_hint">or press space bar</p>
</div>

app/views/welcome/_user_statistics.html.erb
<% @tomatoes_count.each do |time_period, tomatoes_count| %>
  <%= render partial: 'shared/counter', locals: {css_class: time_period, value: tomatoes_count, label: counter_label(time_period)} %>
<% end %>

app/views/welcome/index.html.erb
<%= render :partial => 'tomatoes_timer' %>

<% unless current_user %>
  <%= render :partial => 'public' %>
<% else %>
  <%= render :partial => 'dashboard' %>
<% end %>